name: loongarch64 test

on:
  workflow_dispatch:

jobs:
  linux-loongarch64:
    name: Build linux-loongarch64 Artifacts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: Patcher
      - run: |
            git clone https://github.com/dotnet/runtime.git
            cp -r ./HostFXRPatcher/ ./runtime/HostFXRPatcher
            docker run --rm -v ~/work/HostFXRPatcher/HostFXRPatcher/runtime:/runtime -w /runtime -e ROOTFS_DIR=/crossrootfs/loongarch64/ mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net8.0-cross-loongarch64 bash -c 'git config --global --add safe.directory /runtime ; cd HostFXRPatcher ; pwsh updateVersionReleases.ps1 ; ROOTFS_DIR=/crossrootfs/loongarch64 pwsh ./buildPatch.ps1 -rid linux-loongarch64 -configuration Release -versions ${{ vars.VERSIONS }} -portable -stripsymbols -cross'
      - uses: actions/upload-artifact@v4
        with:
          name: patched-hostfxr_linux-loongarch64
          path: runtime/artifacts-patched
